apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gs-social-app-k8s
  name: gs-social-app-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gs-social-app-k8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gs-social-app-k8s
    spec:
      containers:
      - image: public.ecr.aws/o9p8w3f5/social-app:latest 
        name: gs-social-app-k8s
        resources: {}
        imagePullPolicy: IfNotPresent
status: {}
