apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gs-social-app-k8s
  name: gs-social-app-k8s
spec:
  ports:
  - name: 80-8081
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: gs-social-app-k8s
  type: ClusterIP
status:
  loadBalancer: {}
